dataloader:
  fname: 'C:\Users\Santiago Arciniegas\Desktop\DSI\deep_learning_topics\assignments\assignment_2\data\preproc_data.npz'

train:
  batch_size: 3528
  n_epochs: 200
  patience: 15
  lr: 0.01
  momentum: 0.99
  weight_decay: 0.001

eval:
  batch_size: 100